name: PHP tests
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  php-linter:
    name: PHP Syntax check 7.4|8.1|8.2|8.3|8.4
    runs-on: ubuntu-latest
    steps:
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@v1
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@v1
        with:
              folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@v1
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP syntax checker 8.3
        uses: prestashop/github-action-php-lint/8.3@v1
        with:
          folder-to-exclude: "! -path \"./vendor/*\""
      - name: PHP syntax checker 8.4
        uses: prestashop/github-action-php-lint/8.4@v1
        with:
          folder-to-exclude: "! -path \"./vendor/*\""

  # Check the PHP code follow the coding standards
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}
      - name: Install dependencies
        run: composer install
      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --config tests/php/.php-cs-fixer.dist.php